package com.github.andradenathan.documentprocessor.domain.document.validation.mrz;

import static java.util.Map.entry;

import java.util.Map;

public class CountryCodeResolver {

  private static final Map<String, String> COUNTRY_CODES =
      Map.<String, String>ofEntries(
          entry("ABW", "Aruba"),
          entry("AFG", "Afeganistão"),
          entry("AGO", "Angola"),
          entry("AIA", "Anguilla"),
          entry("ALB", "Albânia"),
          entry("AND", "Andorra"),
          entry("ARE", "Emirados Árabes Unidos"),
          entry("ARG", "Argentina"),
          entry("ARM", "Armênia"),
          entry("ASM", "Samoa Americana"),
          entry("ATA", "Antártida"),
          entry("ATG", "Antígua e Barbuda"),
          entry("AUS", "Austrália"),
          entry("AUT", "Áustria"),
          entry("AZE", "Azerbaijão"),
          entry("BDI", "Burundi"),
          entry("BEL", "Bélgica"),
          entry("BEN", "Benin"),
          entry("BFA", "Burkina Faso"),
          entry("BGD", "Bangladesh"),
          entry("BGR", "Bulgária"),
          entry("BHR", "Bahrein"),
          entry("BHS", "Bahamas"),
          entry("BIH", "Bósnia e Herzegovina"),
          entry("BLR", "Bielorrússia"),
          entry("BLZ", "Belize"),
          entry("BMU", "Bermudas"),
          entry("BOL", "Bolívia"),
          entry("BRA", "Brasil"),
          entry("BRB", "Barbados"),
          entry("BRN", "Brunei"),
          entry("BTN", "Butão"),
          entry("BWA", "Botswana"),
          entry("CAF", "República Centro-Africana"),
          entry("CAN", "Canadá"),
          entry("CHE", "Suíça"),
          entry("CHL", "Chile"),
          entry("CHN", "China"),
          entry("CIV", "Costa do Marfim"),
          entry("CMR", "Camarões"),
          entry("COD", "República Democrática do Congo"),
          entry("COG", "Congo"),
          entry("COK", "Ilhas Cook"),
          entry("COL", "Colômbia"),
          entry("COM", "Comores"),
          entry("CPV", "Cabo Verde"),
          entry("CRI", "Costa Rica"),
          entry("CUB", "Cuba"),
          entry("CYM", "Ilhas Cayman"),
          entry("CYP", "Chipre"),
          entry("CZE", "República Tcheca"),
          entry("DEU", "Alemanha"),
          entry("DJI", "Djibuti"),
          entry("DMA", "Dominica"),
          entry("DNK", "Dinamarca"),
          entry("DOM", "República Dominicana"),
          entry("DZA", "Argélia"),
          entry("ECU", "Equador"),
          entry("EGY", "Egito"),
          entry("ERI", "Eritreia"),
          entry("ESH", "Saara Ocidental"),
          entry("ESP", "Espanha"),
          entry("EST", "Estônia"),
          entry("ETH", "Etiópia"),
          entry("FIN", "Finlândia"),
          entry("FJI", "Fiji"),
          entry("FRA", "França"),
          entry("FRO", "Ilhas Faroe"),
          entry("FSM", "Micronésia"),
          entry("GAB", "Gabão"),
          entry("GBR", "Reino Unido"),
          entry("GEO", "Geórgia"),
          entry("GHA", "Gana"),
          entry("GIB", "Gibraltar"),
          entry("GIN", "Guiné"),
          entry("GMB", "Gâmbia"),
          entry("GNB", "Guiné-Bissau"),
          entry("GNQ", "Guiné Equatorial"),
          entry("GRC", "Grécia"),
          entry("GRD", "Granada"),
          entry("GRL", "Groenlândia"),
          entry("GTM", "Guatemala"),
          entry("GUY", "Guiana"),
          entry("HKG", "Hong Kong"),
          entry("HND", "Honduras"),
          entry("HRV", "Croácia"),
          entry("HTI", "Haiti"),
          entry("HUN", "Hungria"),
          entry("IDN", "Indonésia"),
          entry("IND", "Índia"),
          entry("IRL", "Irlanda"),
          entry("IRN", "Irã"),
          entry("IRQ", "Iraque"),
          entry("ISL", "Islândia"),
          entry("ISR", "Israel"),
          entry("ITA", "Itália"),
          entry("JAM", "Jamaica"),
          entry("JOR", "Jordânia"),
          entry("JPN", "Japão"),
          entry("KAZ", "Cazaquistão"),
          entry("KEN", "Quênia"),
          entry("KGZ", "Quirguistão"),
          entry("KHM", "Camboja"),
          entry("KIR", "Kiribati"),
          entry("KNA", "São Cristóvão e Nevis"),
          entry("KOR", "Coreia do Sul"),
          entry("KWT", "Kuwait"),
          entry("LAO", "Laos"),
          entry("LBN", "Líbano"),
          entry("LBR", "Libéria"),
          entry("LBY", "Líbia"),
          entry("LCA", "Santa Lúcia"),
          entry("LIE", "Liechtenstein"),
          entry("LKA", "Sri Lanka"),
          entry("LSO", "Lesoto"),
          entry("LTU", "Lituânia"),
          entry("LUX", "Luxemburgo"),
          entry("LVA", "Letônia"),
          entry("MAC", "Macau"),
          entry("MAR", "Marrocos"),
          entry("MCO", "Mônaco"),
          entry("MDA", "Moldávia"),
          entry("MDG", "Madagascar"),
          entry("MDV", "Maldivas"),
          entry("MEX", "México"),
          entry("MHL", "Ilhas Marshall"),
          entry("MKD", "Macedônia do Norte"),
          entry("MLI", "Mali"),
          entry("MLT", "Malta"),
          entry("MMR", "Myanmar"),
          entry("MNE", "Montenegro"),
          entry("MNG", "Mongólia"),
          entry("MOZ", "Moçambique"),
          entry("MRT", "Mauritânia"),
          entry("MUS", "Maurício"),
          entry("MWI", "Malawi"),
          entry("MYS", "Malásia"),
          entry("NAM", "Namíbia"),
          entry("NER", "Níger"),
          entry("NGA", "Nigéria"),
          entry("NIC", "Nicarágua"),
          entry("NLD", "Holanda"),
          entry("NOR", "Noruega"),
          entry("NPL", "Nepal"),
          entry("NRU", "Nauru"),
          entry("NZL", "Nova Zelândia"),
          entry("OMN", "Omã"),
          entry("PAK", "Paquistão"),
          entry("PAN", "Panamá"),
          entry("PER", "Peru"),
          entry("PHL", "Filipinas"),
          entry("PLW", "Palau"),
          entry("PNG", "Papua-Nova Guiné"),
          entry("POL", "Polônia"),
          entry("PRI", "Porto Rico"),
          entry("PRK", "Coreia do Norte"),
          entry("PRT", "Portugal"),
          entry("PRY", "Paraguai"),
          entry("PSE", "Palestina"),
          entry("QAT", "Catar"),
          entry("ROU", "Romênia"),
          entry("RUS", "Rússia"),
          entry("RWA", "Ruanda"),
          entry("SAU", "Arábia Saudita"),
          entry("SDN", "Sudão"),
          entry("SEN", "Senegal"),
          entry("SGP", "Singapura"),
          entry("SLB", "Ilhas Salomão"),
          entry("SLE", "Serra Leoa"),
          entry("SLV", "El Salvador"),
          entry("SMR", "San Marino"),
          entry("SOM", "Somália"),
          entry("SRB", "Sérvia"),
          entry("SSD", "Sudão do Sul"),
          entry("STP", "São Tomé e Príncipe"),
          entry("SUR", "Suriname"),
          entry("SVK", "Eslováquia"),
          entry("SVN", "Eslovênia"),
          entry("SWE", "Suécia"),
          entry("SWZ", "Eswatini"),
          entry("SYC", "Seychelles"),
          entry("SYR", "Síria"),
          entry("TCD", "Chade"),
          entry("TGO", "Togo"),
          entry("THA", "Tailândia"),
          entry("TJK", "Tajiquistão"),
          entry("TKM", "Turcomenistão"),
          entry("TLS", "Timor-Leste"),
          entry("TON", "Tonga"),
          entry("TTO", "Trinidad e Tobago"),
          entry("TUN", "Tunísia"),
          entry("TUR", "Turquia"),
          entry("TUV", "Tuvalu"),
          entry("TWN", "Taiwan"),
          entry("TZA", "Tanzânia"),
          entry("UGA", "Uganda"),
          entry("UKR", "Ucrânia"),
          entry("URY", "Uruguai"),
          entry("USA", "Estados Unidos"),
          entry("UTO", "Utopia"),
          entry("UZB", "Uzbequistão"),
          entry("VAT", "Vaticano"),
          entry("VCT", "São Vicente e Granadinas"),
          entry("VEN", "Venezuela"),
          entry("VGB", "Ilhas Virgens Britânicas"),
          entry("VNM", "Vietnã"),
          entry("VUT", "Vanuatu"),
          entry("WSM", "Samoa"),
          entry("YEM", "Iêmen"),
          entry("ZAF", "África do Sul"),
          entry("ZMB", "Zâmbia"),
          entry("ZWE", "Zimbabwe"));

  private CountryCodeResolver() {}

  public static boolean isKnown(String code) {
    if (code == null || code.isBlank()) return false;
    return COUNTRY_CODES.containsKey(code.trim().toUpperCase());
  }

  public static String nameOf(String code) {
    if (code == null || code.isBlank()) return "";
    String normalized = code.trim().toUpperCase();
    return COUNTRY_CODES.getOrDefault(normalized, normalized);
  }
}
