services:
  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: nathan
      POSTGRES_PASSWORD: nathan
      POSTGRES_DB: document_processor
      POSTGRES_PORT: 5433
    ports:
      - "5433:5432"
  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: nathan
      RABBITMQ_DEFAULT_PASS: nathan
    volumes:
      - data:/var/lib/rabbitmq

volumes:
  data:
